#' Diabetes patient records.
#'
#' Fetched from PMLB.
#'
#' @format A data frame with 768 observations and 9 variables.
#'
#' http://archive.ics.uci.edu/ml/datasets/diabetes
#'
"diabetes"

#' Details of 178 nations and their flags.
#'
#' Fetched from PMLB.
#'
#' @format A data frame with 178 observations and 44 variables.
#'
#'
"flags"

#' A retrospective sample of males in a heart-disease high-risk region of the Western Cape.
#'
#' Fetched from PMLB.
#'
#' https://rdrr.io/cran/ElemStatLearn/man/SAheart.html
#' https://www.rdocumentation.org/packages/BeSS/versions/1.0.6/topics/SAheart
#'
#' @format A data frame with 178 observations and 10 variables:
#' \code{Sbp}, \code{Tobacco}, \code{Ldl}, \code{Adiposity}, \code{Famhist}, \code{Typea},
#' \code{Obesity}, \code{Alcohol}, \code{Age} and \code{target}.
#'
#'
"saheart"

#' Mushroom records drawn from
#' The Audubon Society Field Guide to North American Mushrooms.
#'
#' Fetched from PMLB.
#'
#' http://archive.ics.uci.edu/ml/datasets/Mushroom
#' The Audubon Society Field Guide to North American Mushrooms (1981).
#' G. H. Lincoff (Pres.), New York: Alfred A. Knopf
#'
#' @format A data frame with 8124 observations and 23 variables:
#' \code{cap.shape}, \code{cap.surface}, \code{cap.color}, \code{bruises.},
#' \code{odor}, \code{gill.attachment}, \code{gill.spacing}, \code{gill.size},
#' \code{gill.color}, \code{stalk.shape}, \code{stalk.root},
#' \code{stalk.surface.above.ring}, \code{stalk.surface.below.ring},
#' \code{stalk.color.above.ring}, \code{stalk.color.below.ring}, \code{veil.type},
#' \code{veil.color}, \code{ring.number}, \code{ring.type}, \code{spore.print.color},
#' \code{population}, \code{habitat} and \code{target}.
#'
#'
"mushroom"

#' Fate of passengers on the fatal maiden voyage of the ocean liner *Titanic*.
#'
#' Titanic training dataset from titanic::titanic_train.
#'
#' @format A data frame with 891 observations and 12 variables: \code{PassengerId},
#' \code{Pclass}, \code{Name}, \code{Sex}, \code{Age}, \code{SipSp}, \code{Parch},
#' \code{Ticket}, \code{Fare}, \code{Cabin}, \code{Embarked}
#' and \code{Survived} (target).
#'
#' https://www.rdocumentation.org/packages/titanic/versions/0.1.0
#'
"titanic"

#' Waveform database generator.
#'
#' Generator generating 3 classes of waves.
#' Each class is generated from a combination of 2 of 3 "base" waves.
#'
#' @format A data frame with 5000 observations and 41 variables describing the waveform,
#' all of which include noise. The latter 19 attributes are all noise attributes
#' with mean 0 and variance 1.
#'
#' https://datahub.io/machine-learning/waveform-5000
#'
#' Breiman,L., Friedman,J.H., Olshen,R.A., and Stone,C.J. (1984).
#' Classification and Regression Trees. Wadsworth International, pp 49-55, 169.
#'
"waveform"

#' Results of a chemical analysis of wines grown in a specific area of Italy.
#'
#' Three types of wine are represented in the 178 samples,
#' with the results of 13 chemical analyses recorded for each sample.
#'
#' Import with data(wine, package = 'rattle'). Dependent variable: Type.
#' https://rdrr.io/cran/rattle.data/man/wine.html
#' http://archive.ics.uci.edu/ml/datasets/wine
#'
#' @format A data frame with 178 observations and 14 variables:
#' \code{Alcohol}, \code{Malic}, \code{Ash}, \code{Alcalinity},
#' \code{Magnesium}, \code{Phenols}, \code{Flavanoids}, \code{Nonflavanoids},
#' \code{Proanthocyanins}, \code{Color}, \code{Hue}, \code{Dilution}, \code{Proline}
#' and \code{Type} (target).
#'
"wine"

#' Red variant of the Portuguese "Vinho Verde" wine.
#'
#' Fetched from PMLB.
#' Physicochemical and quality of wine.
#'
#' @format A data frame with 1599 observations and 12 variables:
#' \code{fixed.acidity}, \code{volatile.acidity},
#' \code{citric.acid}, \code{residual.sugar}, \code{chlorides}, \code{free.sulfur.dioxide},
#' \code{total.sulfur.dioxide}, \code{density}, \code{pH}, \code{sulphates},
#' \code{alcohol} and \code{target} (quality).
#'
#' http://archive.ics.uci.edu/ml/datasets/Wine+Quality
#'
#' P. Cortez, A. Cerdeira, F. Almeida, T. Matos and J. Reis.
#' Modeling wine preferences by data mining from physicochemical properties.
#' In Decision Support Systems, Elsevier, 47(4):547-553, 2009.
#'
#'
"wine_quality_red"

#' Galaxy dataset for regression.
#'
#' Fetched from PMLB.
#'
#' #' @format A data frame with 323 observations and 5 variables:
#' \code{eastwest}, \code{northsouth}, \code{angle}, \code{radialposition}
#' and \code{target} (velocity).
#'
#' https://www.openml.org/d/690
#'
"galaxy"

#' Synthetic pollen dataset generated by
#' David Coleman at RCA Laboratories in Princeton.
#'
#' Fetched from PMLB.
#'
#' @format A data frame with 3848 observations and 5 variables:
#' \code{ridge}, \code{nub}, \code{crack}, \code{weight}
#' and \code{target} (density).
#'
#' https://www.openml.org/d/529
#'
"pollen"

#' Training dataset.
#' Medical information of Wuhan patients collected between
#' 2020-01-10 and 2020-02-18.
#' Containing NAs.
#'
#' @format A data frame with 375 observations and 77 variables.
#'
#' An interpretable mortality prediction model for COVID-19 patients.
#' Yan et al.
#' https://doi.org/10.1038/s42256-020-0180-7
#' https://github.com/HAIRLAB/Pre_Surv_COVID_19
#'
"train_covid"

#' External test dataset.
#' Medical information of Wuhan patients collected between
#' 2020-01-10 and 2020-02-18.
#'
#' @format A data frame with 110 observations and 7 XGBoost-selected variables:
#' \code{PATIENT_ID}, \code{Lactate dehydrogenase},
#' \code{High sensitivity C-reactive protein}, \code{(%)lymphocyte},
#' \code{Admission time}, \code{Discharge time} and \code{outcome}.
#'
#' An interpretable mortality prediction model for COVID-19 patients.
#' Yan et al.
#' https://doi.org/10.1038/s42256-020-0180-7
#' https://github.com/HAIRLAB/Pre_Surv_COVID_19
#'
"test_covid"


