on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "pkgdown"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error", timeout = 900)
        shell: Rscript {0}
      - name: Build webpage
        run: pkgdown::build_site()
        shell: Rscript {0}
      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !github.event.repository.fork
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

